local zones = {
[0]= { name = "unknown", hostile = true },
[1] = { name = "Phanauet Channel", hostile = true },
[2] = { name = "Carpenters' Landing", hostile = true },
[3] = { name = "Manaclipper", hostile = true },
[4] = { name = "Bibiki Bay", hostile = true },
[5] = { name = "Uleguerand Range", hostile = true },
[6] = { name = "Bearclaw Pinnacle", hostile = true },
[7] = { name = "Attohwa Chasm", hostile = true },
[8] = { name = "Boneyard Gully", hostile = true },
[9] = { name = "Pso'Xja", hostile = true },
[10] = { name = "The Shrouded Maw", hostile = true },
[11] = { name = "Oldton Movalpolos", hostile = true },
[12] = { name = "Newton Movalpolos", hostile = true },
[13] = { name = "Mine Shaft #2716", hostile = true },
[14] = { name = "Hall of Transference", hostile = true },
[15] = { name = "Abyssea - Konschtat", hostile = true },
[16] = { name = "Promyvion - Holla", hostile = true },
[17] = { name = "Spire of Holla", hostile = true },
[18] = { name = "Promyvion - Dem", hostile = true },
[19] = { name = "Spire of Dem", hostile = true },
[20] = { name = "Promyvion - Mea", hostile = true },
[21] = { name = "Spire of Mea", hostile = true },
[22] = { name = "Promyvion - Vahzl", hostile = true },
[23] = { name = "Spire of Vahzl", hostile = true },
[24] = { name = "Lufaise Meadows", hostile = true },
[25] = { name = "Misareaux Coast", hostile = true },
[26] = { name = "Tavnazian Safehold", hostile = false },
[27] = { name = "Phomiuna Aqueducts", hostile = true },
[28] = { name = "Sacrarium", hostile = true },
[29] = { name = "Riverne - Site #B01", hostile = true },
[30] = { name = "Riverne - Site #A01", hostile = true },
[31] = { name = "Monarch Linn", hostile = true },
[32] = { name = "Sealion's Den", hostile = true },
[33] = { name = "Al'Taieu", hostile = true },
[34] = { name = "Grand Palace of Hu'Xzoi", hostile = true },
[35] = { name = "The Garden of Ru'Hmet", hostile = true },
[36] = { name = "Empyreal Paradox", hostile = true },
[37] = { name = "Temenos", hostile = true },
[38] = { name = "Apollyon", hostile = true },
[39] = { name = "Dynamis - Valkurm", hostile = true },
[40] = { name = "Dynamis - Buburimu", hostile = true },
[41] = { name = "Dynamis - Qufim", hostile = true },
[42] = { name = "Dynamis - Tavnazia", hostile = true },
[43] = { name = "Diorama Abdhaljs-Ghelsba", hostile = true },
[44] = { name = "Abdhaljs Isle-Purgonorgo", hostile = true },
[45] = { name = "Abyssea - Tahrongi", hostile = true },
[46] = { name = "Open sea route to Al Zahbi", hostile = true },
[47] = { name = "Open sea route to Mhaura", hostile = true },
[48] = { name = "Al Zahbi", hostile = false },
[49] = { name = "none", hostile = true },
[50] = { name = "Aht Urhgan Whitegate", hostile = false },
[51] = { name = "Wajaom Woodlands", hostile = true },
[52] = { name = "Bhaflau Thickets", hostile = true },
[53] = { name = "Nashmau", hostile = false },
[54] = { name = "Arrapago Reef", hostile = true },
[55] = { name = "Ilrusi Atoll", hostile = true },
[56] = { name = "Periqia", hostile = true },
[57] = { name = "Talacca Cove", hostile = true },
[58] = { name = "Silver Sea route to Nashmau", hostile = true },
[59] = { name = "Silver Sea route to Al Zahbi", hostile = true },
[60] = { name = "The Ashu Talif", hostile = true },
[61] = { name = "Mount Zhayolm", hostile = true },
[62] = { name = "Halvung", hostile = true },
[63] = { name = "Lebros Cavern", hostile = true },
[64] = { name = "Navukgo Execution Chamber", hostile = true },
[65] = { name = "Mamook", hostile = true },
[66] = { name = "Mamool Ja Training Grounds", hostile = true },
[67] = { name = "Jade Sepulcher", hostile = true },
[68] = { name = "Aydeewa Subterrane", hostile = true },
[69] = { name = "Leujaoam Sanctum", hostile = true },
[70] = { name = "Chocobo Circuit", hostile = true },
[71] = { name = "The Colosseum", hostile = true },
[72] = { name = "Alzadaal Undersea Ruins", hostile = true },
[73] = { name = "Zhayolm Remnants", hostile = true },
[74] = { name = "Arrapago Remnants", hostile = true },
[75] = { name = "Bhaflau Remnants", hostile = true },
[76] = { name = "Silver Sea Remnants", hostile = true },
[77] = { name = "Nyzul Isle", hostile = true },
[78] = { name = "Hazhalm Testing Grounds", hostile = true },
[79] = { name = "Caedarva Mire", hostile = true },
[80] = { name = "Southern San d'Oria [S]", hostile = false },
[81] = { name = "East Ronfaure [S]", hostile = true },
[82] = { name = "Jugner Forest [S]", hostile = true },
[83] = { name = "Vunkerl Inlet [S]", hostile = true },
[84] = { name = "Batallia Downs [S]", hostile = true },
[85] = { name = "La Vaule [S]", hostile = true },
[86] = { name = "Everbloom Hollow", hostile = true },
[87] = { name = "Bastok Markets [S]", hostile = false },
[88] = { name = "North Gustaberg [S]", hostile = true },
[89] = { name = "Grauberg [S]", hostile = true },
[90] = { name = "Pashhow Marshlands [S]", hostile = true },
[91] = { name = "Rolanberry Fields [S]", hostile = true },
[92] = { name = "Beadeaux [S]", hostile = true },
[93] = { name = "Ruhotz Silvermines", hostile = true },
[94] = { name = "Windurst Waters [S]", hostile = false },
[95] = { name = "West Sarutabaruta [S]", hostile = true },
[96] = { name = "Fort Karugo-Narugo [S]", hostile = true },
[97] = { name = "Meriphataud Mountains [S]", hostile = true },
[98] = { name = "Sauromugue Champaign [S]", hostile = true },
[99] = { name = "Castle Oztroja [S]", hostile = true },
[100] = { name = "West Ronfaure", hostile = true },
[101] = { name = "East Ronfaure", hostile = true },
[102] = { name = "La Theine Plateau", hostile = true },
[103] = { name = "Valkurm Dunes", hostile = true },
[104] = { name = "Jugner Forest", hostile = true },
[105] = { name = "Batallia Downs", hostile = true },
[106] = { name = "North Gustaberg", hostile = true },
[107] = { name = "South Gustaberg", hostile = true },
[108] = { name = "Konschtat Highlands", hostile = true },
[109] = { name = "Pashhow Marshlands", hostile = true },
[110] = { name = "Rolanberry Fields", hostile = true },
[111] = { name = "Beaucedine Glacier", hostile = true },
[112] = { name = "Xarcabard", hostile = true },
[113] = { name = "Cape Teriggan", hostile = true },
[114] = { name = "Eastern Altepa Desert", hostile = true },
[115] = { name = "West Sarutabaruta", hostile = true },
[116] = { name = "East Sarutabaruta", hostile = true },
[117] = { name = "Tahrongi Canyon", hostile = true },
[118] = { name = "Buburimu Peninsula", hostile = true },
[119] = { name = "Meriphataud Mountains", hostile = true },
[120] = { name = "Sauromugue Champaign", hostile = true },
[121] = { name = "The Sanctuary of Zi'Tah", hostile = true },
[122] = { name = "Ro'Maeve", hostile = true },
[123] = { name = "Yuhtunga Jungle", hostile = true },
[124] = { name = "Yhoator Jungle", hostile = true },
[125] = { name = "Western Altepa Desert", hostile = true },
[126] = { name = "Qufim Island", hostile = true },
[127] = { name = "Behemoth's Dominion", hostile = true },
[128] = { name = "Valley of Sorrows", hostile = true },
[129] = { name = "Ghoyu's Reverie", hostile = true },
[130] = { name = "Ru'Aun Gardens", hostile = true },
[131] = { name = "Mordion Gaol", hostile = true },
[132] = { name = "Abyssea - La Theine", hostile = true },
[133] = { name = "", hostile = true },
[134] = { name = "Dynamis - Beaucedine", hostile = true },
[135] = { name = "Dynamis - Xarcabard", hostile = true },
[136] = { name = "Beaucedine Glacier [S]", hostile = true },
[137] = { name = "Xarcabard [S]", hostile = true },
[138] = { name = "Castle Zvahl Baileys [S]", hostile = true },
[139] = { name = "Horlais Peak", hostile = true },
[140] = { name = "Ghelsba Outpost", hostile = true },
[141] = { name = "Fort Ghelsba", hostile = true },
[142] = { name = "Yughott Grotto", hostile = true },
[143] = { name = "Palborough Mines", hostile = true },
[144] = { name = "Waughroon Shrine", hostile = true },
[145] = { name = "Giddeus", hostile = true },
[146] = { name = "Balga's Dais", hostile = true },
[147] = { name = "Beadeaux", hostile = true },
[148] = { name = "Qulun Dome", hostile = true },
[149] = { name = "Davoi", hostile = true },
[150] = { name = "Monastic Cavern", hostile = true },
[151] = { name = "Castle Oztroja", hostile = true },
[152] = { name = "Altar Room", hostile = true },
[153] = { name = "The Boyahda Tree", hostile = true },
[154] = { name = "Dragon's Aery", hostile = true },
[155] = { name = "Castle Zvahl Keep [S]", hostile = true },
[156] = { name = "Throne Room [S]", hostile = true },
[157] = { name = "Middle Delkfutt's Tower", hostile = true },
[158] = { name = "Upper Delkfutt's Tower", hostile = true },
[159] = { name = "Temple of Uggalepih", hostile = true },
[160] = { name = "Den of Rancor", hostile = true },
[161] = { name = "Castle Zvahl Baileys", hostile = true },
[162] = { name = "Castle Zvahl Keep", hostile = true },
[163] = { name = "Sacrificial Chamber", hostile = true },
[164] = { name = "Garlaige Citadel [S]", hostile = true },
[165] = { name = "Throne Room", hostile = true },
[166] = { name = "Ranguemont Pass", hostile = true },
[167] = { name = "Bostaunieux Oubliette", hostile = true },
[168] = { name = "Chamber of Oracles", hostile = true },
[169] = { name = "Toraimarai Canal", hostile = true },
[170] = { name = "Full Moon Fountain", hostile = true },
[171] = { name = "Crawlers' Nest [S]", hostile = true },
[172] = { name = "Zeruhn Mines", hostile = true },
[173] = { name = "Korroloka Tunnel", hostile = true },
[174] = { name = "Kuftal Tunnel", hostile = true },
[175] = { name = "The Eldieme Necropolis [S]", hostile = true },
[176] = { name = "Sea Serpent Grotto", hostile = true },
[177] = { name = "Ve'Lugannon Palace", hostile = true },
[178] = { name = "The Shrine of Ru'Avitau", hostile = true },
[179] = { name = "Stellar Fulcrum", hostile = true },
[180] = { name = "La'Loff Amphitheater", hostile = true },
[181] = { name = "The Celestial Nexus", hostile = true },
[182] = { name = "Walk of Echoes", hostile = true },
[183] = { name = "Maquette Abdhaljs-Legion", hostile = true },
[184] = { name = "Lower Delkfutt's Tower", hostile = true },
[185] = { name = "Dynamis - San d'Oria", hostile = true },
[186] = { name = "Dynamis - Bastok", hostile = true },
[187] = { name = "Dynamis - Windurst", hostile = true },
[188] = { name = "Dynamis - Jeuno", hostile = true },
[189] = { name = "", hostile = true },
[190] = { name = "King Ranperre's Tomb", hostile = true },
[191] = { name = "Dangruf Wadi", hostile = true },
[192] = { name = "Inner Horutoto Ruins", hostile = true },
[193] = { name = "Ordelle's Caves", hostile = true },
[194] = { name = "Outer Horutoto Ruins", hostile = true },
[195] = { name = "The Eldieme Necropolis", hostile = true },
[196] = { name = "Gusgen Mines", hostile = true },
[197] = { name = "Crawlers' Nest", hostile = true },
[198] = { name = "Maze of Shakhrami", hostile = true },
[199] = { name = "", hostile = true },
[200] = { name = "Garlaige Citadel", hostile = true },
[201] = { name = "Cloister of Gales", hostile = true },
[202] = { name = "Cloister of Storms", hostile = true },
[203] = { name = "Cloister of Frost", hostile = true },
[204] = { name = "Fei'Yin", hostile = true },
[205] = { name = "Ifrit's Cauldron", hostile = true },
[206] = { name = "Qu'Bia Arena", hostile = true },
[207] = { name = "Cloister of Flames", hostile = true },
[208] = { name = "Quicksand Caves", hostile = true },
[209] = { name = "Cloister of Tremors", hostile = true },
[210] = { name = "", hostile = true },
[211] = { name = "Cloister of Tides", hostile = true },
[212] = { name = "Gustav Tunnel", hostile = true },
[213] = { name = "Labyrinth of Onzozo", hostile = true },
[214] = { name = "", hostile = true },
[215] = { name = "Abyssea - Attohwa", hostile = true },
[216] = { name = "Abyssea - Misareaux", hostile = true },
[217] = { name = "Abyssea - Vunkerl", hostile = true },
[218] = { name = "Abyssea - Altepa", hostile = true },
[219] = { name = "", hostile = true },
[220] = { name = "Ship bound for Selbina", hostile = true },
[221] = { name = "Ship bound for Mhaura", hostile = true },
[222] = { name = "Provenance", hostile = true },
[223] = { name = "San d'Oria-Jeuno Airship", hostile = false },
[224] = { name = "Bastok-Jeuno Airship", hostile = false },
[225] = { name = "Windurst-Jeuno Airship", hostile = false },
[226] = { name = "Kazham-Jeuno Airship", hostile = false },
[227] = { name = "Ship bound for Selbina", hostile = true },
[228] = { name = "Ship bound for Mhaura", hostile = true },
[229] = { name = "", hostile = true },
[230] = { name = "Southern San d'Oria", hostile = false },
[231] = { name = "Northern San d'Oria", hostile = false },
[232] = { name = "Port San d'Oria", hostile = false },
[233] = { name = "Chateau d'Oraguille", hostile = false },
[234] = { name = "Bastok Mines", hostile = false },
[235] = { name = "Bastok Markets", hostile = false },
[236] = { name = "Port Bastok", hostile = false },
[237] = { name = "Metalworks", hostile = false },
[238] = { name = "Windurst Waters", hostile = false },
[239] = { name = "Windurst Walls", hostile = false },
[240] = { name = "Port Windurst", hostile = false },
[241] = { name = "Windurst Woods", hostile = false },
[242] = { name = "Heavens Tower", hostile = false },
[243] = { name = "Ru'Lude Gardens", hostile = false },
[244] = { name = "Upper Jeuno", hostile = false },
[245] = { name = "Lower Jeuno", hostile = false },
[246] = { name = "Port Jeuno", hostile = false },
[247] = { name = "Rabao", hostile = false },
[248] = { name = "Selbina", hostile = false },
[249] = { name = "Mhaura", hostile = false },
[250] = { name = "Kazham", hostile = false },
[251] = { name = "Hall of the Gods", hostile = false },
[252] = { name = "Norg", hostile = false },
[253] = { name = "Abyssea - Uleguerand", hostile = true },
[254] = { name = "Abyssea - Grauberg", hostile = true },
[255] = { name = "Abyssea - Empyreal Paradox", hostile = true },
[256] = { name = "Western Adoulin", hostile = false },
[257] = { name = "Eastern Adoulin", hostile = false },
[258] = { name = "Rala Waterways", hostile = true },
[259] = { name = "Rala Waterways [U]", hostile = true },
[260] = { name = "Yahse Hunting Grounds", hostile = true },
[261] = { name = "Ceizak Battlegrounds", hostile = true },
[262] = { name = "Foret de Hennetiel", hostile = true },
[263] = { name = "Yorcia Weald", hostile = true },
[264] = { name = "Yorcia Weald [U]", hostile = true },
[265] = { name = "Morimar Basalt Fields", hostile = true },
[266] = { name = "Marjami Ravine", hostile = true },
[267] = { name = "Kamihr Drifts", hostile = true },
[268] = { name = "Sih Gates", hostile = true },
[269] = { name = "Moh Gates", hostile = true },
[270] = { name = "Cirdas Caverns", hostile = true },
[271] = { name = "Cirdas Caverns [U]", hostile = true },
[272] = { name = "Dho Gates", hostile = true },
[273] = { name = "Woh Gates", hostile = true },
[274] = { name = "Outer Ra'Kaznar", hostile = true },
[275] = { name = "Outer Ra'Kaznar [U]", hostile = true },
[276] = { name = "Ra'Kaznar Inner Court", hostile = true },
[277] = { name = "Ra'Kaznar Turris", hostile = true },
[278] = { name = "", hostile = true },
[279] = { name = "", hostile = true },
[280] = { name = "Mog Garden", hostile = false },
[281] = { name = "Leafallia", hostile = true },
[282] = { name = "Mount Kamihr", hostile = true },
[283] = { name = "Silver Knife", hostile = true },
[284] = { name = "Celennia Memorial Library", hostile = false },
[285] = { name = "Feretory", hostile = true },
[286] = { name = "", hostile = true },
[287] = { name = "", hostile = true },
[288] = { name = "Escha - Zi'Tah", hostile = true },
[289] = { name = "Escha - Ru'Aun", hostile = true },
[290] = { name = "Desuetia - Empyreal Paradox", hostile = true },
[291] = { name = "Reisenjima", hostile = true },
[292] = { name = "Reisenjima Henge", hostile = true },
[293] = { name = "Reisenjima Sanctorium", hostile = true },
[294] = { name = "Dynamis - San d'Oria [D]", hostile = true },
[295] = { name = "Dynamis - Bastok [D]", hostile = true },
[296] = { name = "Dynamis - Windurst [D]", hostile = true },
[297] = { name = "Dynamis - Jeuno [D]", hostile = true },
}
return zones